[package]
name = "vpn-core"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[dependencies]
base64 = "0.23.1"
boringtun = { version = "0.7.1", default-features = false }
rand = "0.8"
thiserror = "2.0.20"
uniffi = { version = "0.32.0", features = ["cli"] }
